seed: 1337
paths:
  raw: data/raw/wiki_comments.csv
  processed: data/processed/
  outputs: outputs/
  models: models/
  lexicon_path: data/lexicon/toxic_lexicon.txt
split:
  test_size: 0.1
  valid_size: 0.1
features:
  word_ngrams: [1, 2]
  char_ngrams: [3, 4]  
  min_df_word: 3
  min_df_char: 3    
  use_lemmatizer: true
  use_raw_feats: true 
  use_profanity_ratio: true
selection:
  enabled: true
  k_best: 150000
tuning:
  enabled: false
  method: bayes
  cv: 3
  n_iter: 15
  n_jobs: -1
  n_points: 4
  scoring: f1
  skip_if_saved: true
train:
  scoring: f1
cache:
  enabled: true
  filename_prefix: tfidf
